CREATE DATABASE ONLINE_ORDER;
USE ONLINE_ORDER;
CREATE TABLE CUSTOMER(CUS_ID INT NOT NULL,
NAME VARCHAR(50),
AGE INT,
primary key(CUS_ID));

INSERT INTO CUSTOMER VALUES(1,'RAM',45),
(2,'RAVI',24),
(3,'SITA',36),
(4,'MOHAN',29),
(5,'SNEGHA',34);

CREATE TABLE ORDER_ITEM(OR_ID INT NOT NULL,
CUS_ID INT ,
PRO_ID INT,
primary key(OR_ID));

INSERT INTO ORDER_ITEM VALUES(1,1,1),
(2,4,3),
(3,2,2),
(4,5,5),
(5,4,3);

CREATE TABLE PRODUCT_ITEM(PRO_ID INT NOT NULL,
PRO_NAME VARCHAR(50) ,
PRIZE VARCHAR(50),
primary key(PRO_ID));

INSERT INTO PRODUCT_ITEM VALUES(1,'SPEAKER','300'),
(2,'HEAR PHONE','150'),
(3,'PHONE','35000'),
(4,'BLUTOOTH HEAD SET','400'),
(5,'PEN','5');

SELECT CUSTOMER.NAME,CUSTOMER.AGE, ORDER_ITEM.PRO_ID FROM CUSTOMER JOIN ORDER_ITEM ON CUSTOMER.CUS_ID = ORDER_ITEM.CUS_ID;

SELECT CUSTOMER.NAME,CUSTOMER.AGE, ORDER_ITEM.PRO_ID,PRODUCT_ITEM.PRO_NAME FROM CUSTOMER JOIN ORDER_ITEM ON CUSTOMER.CUS_ID = ORDER_ITEM.CUS_ID JOIN PRODUCT_ITEM ON ORDER_ITEM.PRO_ID=PRODUCT_ITEM.PRO_ID; 
